### ISSUE TITLE
Server crashes upon game start.

### ISSUE THREAD

**Issue by AdamTragedy** [xaniox/HeavySpleef#18]
http://pastebin.com/bdzn75xe

1.9 server crashed when players started playing in one of the spleef arenas. This is the crash log. Thanks.

**Comment by xaniox** [comment]
This error seems to be really strange and I currently have no idea why this happens. 

I took a look at the minecraft server source code to figure out exactly where the error you posted is caused, but it just points me to a line of code which is probably irrelevant to this issue.

Maybe we could meet up on your server to get a better view on what exactly is causing the server crash.

**Comment by xaniox** [comment]
No response after more than a month now. Closing this issue now.
