### ISSUE TITLE
Problem When Creating Arenas

### ISSUE THREAD

**Issue by DragonLordIX** [xaniox/HeavySpleef#19]
Hello I use This plugin alot , for some reason when i create a lobby on a arena I time out and the server freezes or crashes i have to kill the server to re-join

**Comment by xaniox** [comment]
Could you please check your log for a crash error? Please post it on pastebin.com and include a link to it.

**Comment by DragonLordIX** [comment]
Through the console i'm getting this error

9:37:17 PM CONSOLE: [INFO] DragonLordIX issued server command: /spleef addwall Arena1
9:38:21 PM CONSOLE: FATAL]: A single server tick took 60.04 seconds (should be max 0.05)
9:38:21 PM CONSOLE: FATAL]: Considering it to be crashed, server will forcibly shutdown.

**Comment by DragonLordIX** [comment]
http://pastebin.com/yt8gB2yZ

**Comment by DragonLordIX** [comment]
Not sure if this helps
http://pastebin.com/yt8gB2yZ

**Comment by DragonLordIX** [comment]
Still having the issue is there any fix

**Comment by xaniox** [comment]
This error has been reported to me several times but unfortunately I don't know what exactly is causing it. I'm pretty sure it is related to the issue reported [here](http://dev.bukkit.org/bukkit-plugins/heavyspleef/tickets/255-heavyspleef-signs/). 

We might be to resolve your issue on your server. Could you please tell me your server address? If you don't want to share your server address publicly please send me a PM on spigotmc.org.
