### ISSUE TITLE
build #283 server hang issue

### ISSUE THREAD

**Issue by frizzbee30** [xaniox/HeavySpleef#20]
Hi, I know it's not 'release' version, but just to let you know that #283 hangs during server boot. It 's reproducible and resolved by rolling back to the 27/3 version.  :)

**Comment by xaniox** [comment]
I experienced a similar issue while I was testing build #283 with a server owner. I tried running it on my localhost, but I did not experience a hang during server startup (even though it would make sense, since commands did absolutely nothing while testing it with the server owner).

Could you please send me the startup log of HeavySpleef or tell me where exactly HeavySpleef is hanging?

**Comment by frizzbee30** [comment]
Hi, pasted below. I don't know if it's very helpful, but it does hang at the same point every time. I'm wondering if it's when it's loading the add on's, or connecting to MySQl (although that should just 'fail')

http://pastebin.com/iLCjh3cG

That section with normal load

http://pastebin.com/LwELXrJG

**Comment by xaniox** [comment]
The strange thing about this is that I did not change anything regarding the startup of HeavySpleef. Your first paste only contains the message that HeavySpleef is being loaded, there is absolutely no enable message.

Are you sure you included the entire log?

**Comment by frizzbee30** [comment]
Yea, that's as far as it got, no errors or anything, I'm presuming the hang failed to write anything, although the server shut is there (which demostrates it's a complete paste). There's no crash log etc as I shut it down.
 I only noticed as I was actually watching mem usage and noticed RAM was around 60% with zero CPU load , I then swapped to console and noticed the halt

**Comment by frizzbee30** [comment]
I'll see if I can get it to do the same on the test server later and produce anything usable.

**Comment by xaniox** [comment]
Please try build #283 and see if it resolves the issue.

**Comment by frizzbee30** [comment]
#284 loads fine :)
