### ISSUE TITLE
Problem with flags

### ISSUE THREAD

**Issue by pamehabai6** [xaniox/HeavySpleef#22]
So sometimes when i try to setup an arena flag i get this error: http://pastebin.com/9gynYrYf 

I think it has something to do with uppercase letters. For example if i have a spleef arena named Default and i try to set the flag as follows /spleef flag Default lobby, i get the error, while if i try to set it as /spleef flag default lobby it sets up fine but i am not sure. 
I dont really mind this i just thought you should know.
Thanks

**Comment by xaniox** [comment]
This issue has been fixed by build #288: [https://ci.xaniox.de/job/HeavySpleef/](https://ci.xaniox.de/job/HeavySpleef/)
