### ISSUE TITLE
Not able to break floor instantly

### ISSUE THREAD

**Issue by JackzTaEpic** [xaniox/HeavySpleef#25]
I have setup a basic arena and for some reason I cannot instant break the floor. I can break anything on the floor (like lamps) but not instant break. The default value (true) for instant break is on. Splegg works fine, I also tried splegg off.

(Side note: Does splegg work with instant-block-break?)

(Side note 2: I had to post it here, bukkitDev internal server error)

**Comment by xaniox** [comment]
That looks pretty strange to me. If Splegg wouldn't work too, I would guess that the floors have been misconfigured, but since it's working in this case I really don't know what could cause that.

Could you send me your server ip, so we can have a closer look at it?

**Comment by JackzTaEpic** [comment]
I got it working, I tried using mySQL later that day and screwed it up and
so I reinstalled it and I guess a flag broke it. Works now

*Jackz*
Server Website <http://jackzcraft.net> | Twitter
<http://twitter.com/jackzminecraft> | JackzCraft Support Email
<support@jackzcraft.com>

**Comment by xaniox** [comment]
Now that is a quick response... Glad that you got it working again :)
I'll close this issue now.
