### ISSUE TITLE
MySQLtimeouts

### ISSUE THREAD

**Issue by frizzbee30** [xaniox/HeavySpleef#27]
Hi we are running spigot 1.9.4 latest commit and spleef dev version 297

Only a minor issue, we have a holographic stats dispaly, and I don't know if this is contributing to the issue, however we have an externally hosted MySQL database with around 15 plugins running on it. We are however getting a lot of timeouts with heavyspleef. Could you possibly increase the tolerance or timeout interval for the plugin? it doeas read the stats, but is continually spamming the console. it can also take around 5 seconds or so to catch up, if the statsboard is in a chunk that hasn't been loaded for a while.

Pastebin of error below

Thanks

http://pastebin.com/w53Y3q0V

**Comment by xaniox** [comment]
Sorry for my super-late response, but I now added an option to specify the connection timeout for sql in the database configuration. Please update to the latest development build #298 and delete your old database-configuration.yml to generate a new one.

You should find a corresponding node at the end of the file.

**Comment by frizzbee30** [comment]
Thanks, will test asap. Thanks for all the development, it's a great plugin :)
