### ISSUE TITLE
1.10 Error

### ISSUE THREAD

**Issue by Sadisticrabbit** [xaniox/HeavySpleef#28]
Hi There,

Updated to 1.10 now getting this on join.. 

17.06 06:16:58 [Server] INFO at java.lang.Thread.run(Unknown Source) [?:1.7.0_72]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.run(MinecraftServer.java:571) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.C(MinecraftServer.java:672) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.DedicatedServer.D(DedicatedServer.java:399) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.MinecraftServer.D(MinecraftServer.java:733) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.SystemUtils.a(SourceFile:45) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at java.util.concurrent.FutureTask.run(Unknown Source) [?:1.7.0_72]
17.06 06:16:58 [Server] INFO at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source) [?:1.7.0_72]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnectionUtils$1.run(SourceFile:13) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.a(PlayerConnection.java:1186) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at net.minecraft.server.v1_10_R1.PlayerConnection.handleCommand(PlayerConnection.java:1351) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at org.bukkit.craftbukkit.v1_10_R1.CraftServer.dispatchCommand(CraftServer.java:646) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:141) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at org.bukkit.command.PluginCommand.execute(PluginCommand.java:44) [Spigot110.jar:git-Spigot-c55900f-9856d8a]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.commands.base.CommandManagerService.onCommand(CommandManagerService.java:199) [HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.commands.base.CommandContainer.execute(CommandContainer.java:152) [HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.commands.base.DefaultCommandExecution.execute(DefaultCommandExecution.java:82) [HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.commands.base.DefaultCommandExecution.invokeMethod(DefaultCommandExecution.java:148) [HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.7.0_72]
17.06 06:16:58 [Server] INFO at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
17.06 06:16:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.7.0_72]
17.06 06:16:58 [Server] INFO at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.7.0_72]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.commands.CommandJoin.onJoinCommand(CommandJoin.java:59) ~[HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.core.game.JoinRequester.request(JoinRequester.java:174) ~[HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.core.game.JoinRequester$2.onSuccess(JoinRequester.java:90) ~[HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.core.game.Game.join(Game.java:596) ~[HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.core.game.Game.join(Game.java:685) ~[HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at de.xaniox.heavyspleef.core.player.PlayerStateHolder.updateState(PlayerStateHolder.java:219) ~[HeavySpleef.jar:?]
17.06 06:16:58 [Server] INFO at java.lang.System.arraycopy(Native Method) ~[?:1.7.0_72]
17.06 06:16:58 [Server] INFO java.lang.ArrayIndexOutOfBoundsException
17.06 06:16:58 [Server] ERROR Unhandled exception executing command "join"

**Comment by Sadisticrabbit** [comment]
FYI: Running latest dev built.

**Comment by xaniox** [comment]
Seems like HeavySpleef messes up the internal Minecraft version detection if it is unknown. I implemented a more adaptable system which should also sustain compatibility with future versions of Minecraft.

Updating to the latest development build #298 should resolve your issue.

**Comment by Sadisticrabbit** [comment]
Thank you. I will download and try. Thanks.
