### ISSUE TITLE
Plugin throws lots of errors but it ingame it works

### ISSUE THREAD

**Issue by kikelkik** [xaniox/HeavySpleef#29]
I installed and configured heavyspleef and in game it works without any conflicts.
But when I look at the console window and at the server log, the plugin causes a lot of errors whilist playing spleef. Here's an excerpt: http://pastebin.com/XHVem0Gv

1.10 paperspigot server configuration ('Config'): https://timings.aikar.co/v2/?id=f1b31a50f91b4ae396ae429b28cfec73&section=plugins

heavyspleef folder: https://www.dropbox.com/sh/dvpyb4stnq68e30/AADd6cyBcAKZxthP1R0aOB6La?dl=0

**Comment by xaniox** [comment]
Seems like I forgot to add a translation string for the warmup mode. I implemented a fix in the latest development build #300.

https://ci.xaniox.de/job/HeavySpleef/

**Comment by kikelkik** [comment]
Thanks you fixed it! :D
