### ISSUE TITLE
Inventory loss

### ISSUE THREAD

**Issue by flapjack1968** [xaniox/HeavySpleef#30]
Hi - I sent you a private message on Spigot.org as well so sorry for the duplicate.  I just saw this link for tickets.  We have created our first game but are having a few problems:

1) players lose inventory after game ends (only keeping the shovel)
2) players are not moved from /god or creative to survival automatically.

I looked, but don't see a reference to this.  Any ideas?

**Comment by xaniox** [comment]
Seems like I actually messed up the version check for inventory storing/restoring with this update. A single '=' was required to fix this bug, I probably have to release a hotfix version. 

The latest development build #301 contains the mentioned fix: https://ci.xaniox.de/job/HeavySpleef/

**Comment by flapjack1968** [comment]
Thanks - this fixed the inventory issue, but now it won't provide a shovel when the game starts.  I ran the flag command again and reloaded the plugin, but still nothing.  

Also, the win flag command isn't being recognized but not sure if that is a big deal.

**Comment by xaniox** [comment]
Just tested those two flags on my test server and I had no issues. Maybe we could solve your issue on your server, but it might be good to know at which time you're usually online :)

**Comment by flapjack1968** [comment]
In the US, Eastern time zone.  Are you as well?

**Comment by xaniox** [comment]
I'm currently in CEST (Central European Summer Time) so I'm available from 6am EST to approx. 5pm EST.

**Comment by flapjack1968** [comment]
Fantastic – I have business calls for the next couple hours, but I’ll ping you after to see if you’re available.  Thanks for the quick responses!!

 

Flapjack1968

**Comment by flapjack1968** [comment]
Matthias - My second call cancelled so I'm available if you are.

**Comment by xaniox** [comment]
Issue has been fixed in the latest commit which introduces an option to enable / disable adventure mode.

89c633d59c746590dd60abe7ec1454a3c6d672cf
