### ISSUE TITLE
Add-ons

### ISSUE THREAD

**Issue by zelotbe** [xaniox/HeavySpleef#32]
Hi, I created an Addons folder because there wasn't one then I putted the LeaderboardExtension in it.
I did /spleef addons list and it say's that no plugins are in the folder. Bug or am I doing something wrong?

**Comment by xaniox** [comment]
You should be able to find the addons folder under /plugins/HeavySpleef/addons. If there is still no folder please ensure that you have the latest version of HeavySpleef installed and there are no HeavySpleef related errors in the console.

**Comment by xaniox** [comment]
No response for over a month. I assume this issue has been resolved, if not please re-open it.
