### ISSUE TITLE
Remove space character after prefix.

### ISSUE THREAD

**Issue by molor** [xaniox/HeavySpleef#33]
Please remove it. nothing should separate the prefix. If I need space,
I'll add it to the prefix, but now I don't need it, but remove it is impossible..

https://github.com/xaniox/HeavySpleef/blob/master/heavyspleef-core/src/main/java/de/xaniox/heavyspleef/core/HeavySpleef.java#L208

**Comment by xaniox** [comment]
Requested changes implemented in the latest development build #305 (will reset your config)
https://ci.xaniox.de/job/HeavySpleef/
