### ISSUE TITLE
Min Players Bugged

### ISSUE THREAD

**Issue by CiccioTambu** [xaniox/HeavySpleef#36]
Hi, despite having set the minimum player to start the game 6, the minimum player that only requires about 20. I can not understand what is wrong.

In addition, there is an Italian translation of the plugin?

Sorry for the English, but they are Italian.
I await response.
Cordially,
- CiccioTambu

**Comment by xaniox** [comment]
Hey,

sorry for my late response. I've just tested the min-players flag once again and it still works as desired. Having it set to 3 I'm not able to start the game with 2 players. 
Could you explain your issue a bit more detailed? That would be very helpful :)

**Comment by xaniox** [comment]
No response for almost two months. I assume this issue has been resolved, if not please reopen this issue or create a new one.
