### ISSUE TITLE
The player leave the spectate mode not go to leavepoint

### ISSUE THREAD

**Issue by cocomine** [xaniox/HeavySpleef#37]
player leave the spectate mode not go to leavepoint!
Is setting the problem?

**Comment by xaniox** [comment]
The "leavepoint" flag is intended for game use only. There is currently no option to set the leaving point for spectators as they will always be sent back to there recent position.

I might consider adding this flag in future if you suggest so.

**Comment by cocomine** [comment]
I would like to be able to quickly add the spectate mode leave point.

**Comment by xaniox** [comment]
Implemented in the latest development build. Totally forgot to inform you about that.

https://ci.xaniox.de/job/HeavySpleef
