### ISSUE TITLE
Double Health Bug

### ISSUE THREAD

**Issue by nicuch** [xaniox/HeavySpleef#39]
If a player have one (or multiple) item(s) with attribute max-health (+20) before entering on lobby (or in-game) when he leaves the game, the life will be double
info: I used Itemizer plugin for making items with attributes.
[https://www.youtube.com/watch?v=Un2_8EbnPns](url)

I think you save the health of a player (i didn't check)
you can use this on saving:
[http://pastebin.com/e7mJ2cj1](url)

**Comment by xaniox** [comment]
Fixed by merging pull request #40 
Thanks!
