### ISSUE TITLE
Players cant leave, permission node added.

### ISSUE THREAD

**Issue by UltimaA380** [xaniox/HeavySpleef#43]
So I have the permission node, and players can't leave with or without sign. These are the perms i've added:

    - heavyspleef.join
    - heavyspleef.sign.join
    - heavyspleef.join.arena1
    - heavyspleef.leave.arena1
    - heavyspleef.leave
    - heavyspleef.sign.leave
    - heavyspleef.vote
    - heavyspleef.sign.vote
    - heavyspleef.help.user
    - heavyspleef.spectate
    - heavyspleef.statistic

**Comment by xaniox** [comment]
These are the permission nodes for HeavySpleef 1.x. Please use the new permission nodes as documented on BukkitDev: https://dev.bukkit.org/bukkit-plugins/heavyspleef/pages/documentation/heavyspleef-2-0/commands-permissions/

**Comment by UltimaA380** [comment]
Thank you so much.
