### ISSUE TITLE
Inventory GUI addon - Restrict putting items

### ISSUE THREAD

**Issue by Ghostlyr** [xaniox/HeavySpleef#49]
Any item can be tucked in GUI addon inventory by a simple move and shift-click, then irrecoverably lost, because it can not be taken back.

Tested on latest addon and plugin dev builds.

**Comment by xaniox** [comment]
This seems to be an 1.7.10 specific HeavySpleef issue. I fixed this bug in the latest development build.
https://ci.xaniox.de/job/HeavySpleef
