### ISSUE TITLE
Can you add permissions to use [vote] and other signs separately?

### ISSUE THREAD

**Issue by molor** [xaniox/HeavySpleef#57]
Hello. On my server, players can pick up and throw each other using _.setPassenger()_. And if player, who picked up another player, type _/spl join_, formally it will be registered in the game, but will not be in the lobby (players with passengers cannot be teleported using _.teleport()_. Seriously, this is bukkit/spigot limitation (or bug?)). As a result, players can stay at home (for example), thereby win the game and increase his rating.

To solve this problem, I removed permission to the _/spl vote_ command and created a **[vote]** sign that the players could vote for the beginning of the game only being in the lobby. But there is another problem: players have no permision to use it.

Can you add permissions to use **[vote]** and other signs separately, please? for example, _heavyspleef.sign.vote_. Because of this problem I had to close spleef arena and players unhappy..
Thanks

**Comment by xaniox** [comment]
Hey,

there are already sign specific permissions available. Just take a look at the commands & permissions documentation page :)

https://dev.bukkit.org/projects/heavyspleef/pages/documentation/heavyspleef-2-0/commands-permissions

The permissions are:

- heavyspleef.player.sign.join
- heavyspleef.player.sign.leave
- heavyspleef.player.sign.vote
- heavyspleef.player.sign.spectate
- heavyspleef.player.sign.start
