### ISSUE TITLE
JoinGUI flag does not work properly

### ISSUE THREAD

**Issue by Ghostlyr** [xaniox/HeavySpleef#58]
Flag does not changing nothing except item ID:

![image](https://cloud.githubusercontent.com/assets/8511068/23516388/44b871a8-ff97-11e6-8bc8-bc09e7af7d10.png)
![image](https://cloud.githubusercontent.com/assets/8511068/23516420/592e68d6-ff97-11e6-9886-cdd03bb2ca38.png)

And value of "amount" generally does not want be registered in persistence file.

**Comment by xaniox** [comment]
Fixed in the latest development built. HeavySpleef will now mind item titles and lores if they are set explicitly.
