### ISSUE TITLE
1.13.1 Support

### ISSUE THREAD

**Issue by TheoRetisch1** [xaniox/HeavySpleef#76]
Hejo,
HeavySpleef obviously doesn't work with the new paper version 1.13.1 due to the heavy changes. A startup error get logged and the plugin get disabled: https://pastebin.com/nFpgH89W

For some years you have owned the only working puplic Spleef plugin. Dont't let this wonderful project die.

~Theo

**Comment by BaxAndrei** [comment]
He's right, please do not let this project die.

**Comment by Doskii** [comment]
Why do all the good plugins always have to die. My server has basically become swiss cheese due to the unstable nature of minecraft servers and their plugins :(

**Comment by TheoRetisch1** [comment]
Yes, sad story! At the moment every version change becomes more stressful. But what can you expect from leisure projects xD

**Comment by TheoRetisch1** [comment]
HeavySpleef is obviously dead. I recommend SpleefX to anyone who is currently looking for a good Spleef plugin: https://www.spigotmc.org/resources/%E2%99%9B-spleefx-%E2%99%9B-spleef-splegg-bow-spleef-perks-upgrades-shops-and-much-much-more.73093/
